import {createSlice} from "@reduxjs/toolkit";

//Create the slice
const counterSlice = createSlice({
    name: "counter", //Name of the slice
    initialState: 0, //Initial state of the counter
    reducers: {
        increment: (state, action) => state + (action.payload || 1), //Increment by payload if provided otherwise 1
        decrement: (state) => state - 1, //Decrement action
        reset: () => 0, //Reset action
    },
});

//Export the action (automatically generated by createSlice)
export const { increment, decrement, reset } = counterSlice.actions;

//Export the reducer to configure the store
export default counterSlice.reducer;